name = "maze-ssr"
type = "javascript"
workers_dev = true
compatibility_date = "2022-04-29"

[site]
bucket = "public"
entry-point = "cloudflare"

[build]
command = ""

# for wrangler dev
# [build]
# command = "deno task build"
# watch_dir = "pages"

[build.upload]
format = "service-worker"