name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.21.0
      - name: Build
        run: deno run -A --no-check https://raw.githubusercontent.com/herudi/maze/dev-0.0.7/cli/build.ts --my-split
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "maze-ssr"
          entrypoint: "./server.ts"