name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.21.0
      - name: Build
        run: deno task build
      - name: Deploy To Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "maze-ssr"
          entrypoint: "./.maze/server.ts"
      - name: Deploy To Cloudflare Workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}